# Generated by Django 3.1.6 on 2021-02-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='registrationNumber',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
