# Generated by Django 3.1.6 on 2021-02-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210217_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.CharField(blank=True, default='consultation', max_length=100, null=True),
        ),
    ]
